blank_issues_enabled: true
contact_links:
  - name: "Discord #feature-requests"
    url: https://discord.gg/hxeQC5wxzf
    about: Please discuss feature requests here before filing an issue.
  - name: "Discord #bug-reports for bugs"
    url: https://discord.gg/cw84Ae5UQt
    about: Please discuss bugs here before filing an issue.
